name: Build Windows Executable

  on:
    workflow_dispatch:  # Manual trigger
    push:
      branches: [ main, master ]

  jobs:
    build-windows:
      runs-on: windows-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flask pandas selenium webdriver-manager openpyxl

      - name: Build Windows executable
        run: |
          python build_windows_exe.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: whatsapp-automation-windows-standalone
          path: WhatsApp-Automation-Windows-Standalone.zip
          retention-days: 30
